### ISSUE TITLE
ESP32 compile problem:  no member allow_pd

### ISSUE THREAD

**Issue by askuric** [askuric/Arduino-FOC#483]
**Describe the bug**
ESP32 family of MCUs does not compile with the library version v2.3.5. The compilation error is  no member `allow_pd`.

**Describe the hardware setup**
- Which microcontroller: 
Any ESP32 family MCU with MCPWM support

**Reason** 
The libray version v2.3.5 is based on Arduino-esp32 framework versions v3.2+. If you have the earlier version, the code is not compatible and will produce this error when compiling. 

SimpleFOClibrary v2.3.6 will allow for backward compatibility so if you have this error there are two ways to solve it:
- upgrade the SimpleFOClibrary to v2.3.6
- or upgrade the arduino-esp32 framework to the version above v3.2
